### ISSUE TITLE
could I use inline keyboad on the fly with your package?

### ISSUE THREAD

**Issue by mrmrn** [tje3d/Telegram#1]
hi,
thank you for the package.
could I use inline keyboad on the fly with your package like [this](https://core.telegram.org/file/811140217/1/NkRCCLeQZVc/17a804837802700ea4) by using this package?
and how to implement that?

**Comment by tje3d** [comment]
Hi,
Sure you can build any possible telegram message, but i'l make it much easier soon. Here is an example of message with inlineKeyboardMarkup: 

```
<?php

use Tje3d\Telegram\Telegram;

$telegram = new Telegram('BOT_TOKEN');

$result = $telegram->requestBuilder()
    ->text('Something')
    ->chat_id('CHAT_ID')
    ->reply_markup(
        [
            "inline_keyboard" => [
            	[
            		[ "text" => "Btn1", "callback_data" => 'c1' ], [ "text" => "Btn2", "callback_data" => 'c2' ]
            	],
            	[
            		[ "text" => "Btn3", "callback_data" => 'c3' ], [ "text" => "Btn4", "callback_data" => 'c4' ]
            	]
            ],
        ]
    )
    ->sendMessage();
```

**Comment by mrmrn** [comment]
I will working on it and report the results.
Is there any example of using your code?
thank you moen.
ممنون معین عزیز بابت پکیج. یه تست میزنم و حتما به دوستان میگم استار بدن و استفاده کنن.

**Comment by tje3d** [comment]
خواهش میکنم و امیدوارم بدردتون بخوره.
انشالله تا چندروز دیگه وقتم خالی میشه و ساختار کد رو خیلی بهینه تر و خواناتر میکنم.

**Comment by mrmrn** [comment]
حتما.
اگر بتونم همون دکمه ای که عکس دادم رو اکی کنم باهاش قطعا از همین استفاده میکنم بدون شک.
در کل ممنون از زحمتی که کشیدی داداش

**Comment by tje3d** [comment]
نمونه ای که دادم باهاش اینو ساختم:
<img width="191" alt="screen shot 2017-04-07 at 02 01 38" src="https://cloud.githubusercontent.com/assets/5238989/24776479/35fe0064-1b36-11e7-9968-0f8efd208b46.png">

**Comment by mrmrn** [comment]
من میخوام یه چیز تو مایه های همون عکس باشه. یعنی انگار ۳۰ تا گزینه داری میخوای نشون بدی. تو ۱۰ تا صفحه ۳ تایی میاری نشون میدی یوزر هی میره صفحه بعد. یه چیزی شبیه پیجینیشن هست.
