### ISSUE TITLE
Can I make a method for each command?

### ISSUE THREAD

**Issue by mrmrn** [tje3d/Telegram#11]
Can I make a command for each bot command? or I should create one method and use it for handle all commands?

**Comment by tje3d** [comment]
Sorry i cant understand your question. Can you explain more?

**Comment by mrmrn** [comment]
منظور من این بود که هر کامندی یه متد جداداشته باشه.
کل بات توی یه متد نوشته نشه و یجور هندل کنیم هر کامند رو بفرستیم رو یک متد.

**Comment by tje3d** [comment]
این ساختار باید توسط خودتون ایجاد بشه.
از اونجایی که این پکیج فقط برای ساده کردن فراخوانی متدهاست، قابلیت مدنظر شمارو نداره.
