### ISSUE TITLE
I can not install the package on laravel 5.4

### ISSUE THREAD

**Issue by mrmrn** [tje3d/Telegram#2]
I want to install the package on laravel 5.4 but It gaves me:
`composer require tje3d/telegram`
```
  [InvalidArgumentException]                                                   
  Could not find package tje3d/telegram at any version for your minimum-stabi  
  lity (stable). Check the package spelling or your minimum-stability          

```

**Comment by tje3d** [comment]
this should works:
`composer require tje3d/telegram:dev-master`

**Comment by mrmrn** [comment]
I used `composer require tje3d/telegram @dev` and it worked.
also publishing worked fine.
thank you for your fast response.

**Comment by mrmrn** [comment]
I will write a fast document for using in laravel as soon as possible.

**Comment by tje3d** [comment]
Please check dev branch too (https://github.com/tje3d/Telegram/tree/dev)
