### ISSUE TITLE
how to forgot a non answered request?

### ISSUE THREAD

**Issue by mrmrn** [tje3d/Telegram#5]
I have a serious problem with my bot.
when a request is not answered , bot sticked into the request and even user can not /start or...
how can I catch errors and say to telegram bot api to neglect that request and run next request?

there are many causes of errors in bot, user can stop and block it, my code maybe have bugs or even the webservice I am using can not respond in that time.
how can I catch them and avoid bot to stick in this error.

**Comment by tje3d** [comment]
Its totally depend on your app structure, but you can specify expire time for any message.

**Comment by mrmrn** [comment]
thank you for your fast response,
I dont know how to specify expire time for messages?
but how can I try catch any kind of error and send response `200` to telegram?

**Comment by mrmrn** [comment]
I think the code I need is something like this:

> try {
> 
>             $telegram->sendMessage([
>                 'chat_id'                  => '<PERSONS_ID>',
>                 'text'                     => 'Here is some text',
>             ]);
> 
>         } catch (TelegramResponseException $e) {
> 
>             $errorData = $e->getResponseData();
> 
>             if ($errorData['ok'] === false) {
>                 $telegram->sendMessage([
>                     'chat_id' => '<ADMINISTRATOR ID>',
>                     'text'    => 'There was an error for a user. ' . $errorData['error_code'] . ' ' . $errorData['description'],
>                 ]);
>             }
>         }
> 

or even more general.

**Comment by tje3d** [comment]
As this is not a package problem, i'l closed it for now. Reopen it if you need any help.
