### ISSUE TITLE
how to set webhook correctly?

### ISSUE THREAD

**Issue by mrmrn** [tje3d/Telegram#6]
I created a route like this: `Route::get('/setwebhook', 'BotController@handle');` and the methos is this:
```
   public function handle()
  {		
    	$telegram = new Telegram('306779470:AAHKlLEbwnzv-2t2OjUr2hBynhAqkG2owTY');
	$result = $telegram->requestBuilder()
	    ->setWebhook('https://x.y.ir/');
	    return 'webhook is set';
   }
```
and `https://x.y.ir/` is the route of my project. so I used this url : `Route::post('/', 'BotController@postWebhook');` 
the method is:
```
public function postWebhook($request)
   {
   	$alldata=\Request::all();
   	dd($request);
   }
```

I think what I did is right but it gave me this error in laravel:
MethodNotAllowedHttpException in RouteCollection.php line 251

**Comment by tje3d** [comment]
Make a command to set webhook instead of route.

Your function with a little change should works, lets try to store received message in a file and check if there is any problem:
```
use Illuminate\Http\Request;
...

public function postWebhook(Request $request)
{
	$alldata = $request->all();
	\Storage::put('log.txt', $alldata);
	// Now check storage/app/log.txt
}
```

**Comment by mrmrn** [comment]
what do you mean 
> Make a command ?

**Comment by tje3d** [comment]
https://laravel.com/docs/5.4/artisan#writing-commands

**Comment by mrmrn** [comment]
thank you, I deleted webhook for now, as soon as possible I will working on it and report the outcome.

**Comment by marn65** [comment]
@tje3d 
Dear moen, in php I dont have access to artisan. how can I fire a command and set webhook.
thanks.

**Comment by tje3d** [comment]
@marn65 that `command` thing is one of the [laravel framework](https://github.com/laravel/laravel) features. you need to set webhook once per project and that's why i pointed to that feature.

You can always set/change webhook easy like this:
```
$bot = new \Tje3d\Telegram\Bot($token);
$bot->setWebhook('https://sld.tld');
```

**Comment by marn65** [comment]
in laravel, can I make a command in my local and run it in my local  terminal or it must run in  the server?
why I cant use a route for it as you mentioned for PHP developers.

**Comment by tje3d** [comment]
You can always use route for this purpose but because it is a onetime job, i think the best way is using a installation command.
