### ISSUE TITLE
how to catch any kind of error in a telegram bot code?

### ISSUE THREAD

**Issue by marn65** [tje3d/Telegram#7]
Hi.
how can I send `ok` to telegram api against any errors or mistake?
thanks.
or in other word when I using this package how can I use try catch like this
```
public function getInline()
{  
     try
     {
       600 lines of code
       if (haserror)
       {
                 throw new Exception('An ERROR.');
       }
       catch(Exception $ex)                                                   
    {                                                                      
             echo 'Error : '.$ex -> getMessage();                               
        }
  }
}
```
what should I do for ` if (haserror)` part?

**Comment by tje3d** [comment]
What you mean by sending `ok`?

When telegram send any updates to your webhook url, its require an HTTP Reponse with Header Status 200. if anything instead of 200 returns, telegram will send updates again and again.

**Comment by marn65** [comment]
yeah.
I want to try catch any error and then if the request is experiencing  errors say to telegram its ok.go to next request.
I mentioned a piece of code in first question.

**Comment by marn65** [comment]
I can send HTTP response with Header Status 200 to telegram or send a message to user that bot have some problem now, try it later.
but how can I catch his errors?
or as you said in another issue how to specify expire time for that message by your package?

**Comment by tje3d** [comment]
So you want catch errors when sending methods to chatID ( like chatID not exists and... ) ?

If so, as we use GuzzleHttp for http request's, if any http problems occur, it will throw one of the [GuzzleHttp Exceptions](http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions).
And you can catch it when you are sending any method:

If your bot token is wrong or you have any method mistakes, `sendMethod` function will throw a `\GuzzleHttp\Exception\RequestException`

```
try {

	$bot->sendMethod(
		(new \Tje3d\Telegram\Methods\Text())
		    ->text('test')
		    ->chat_id($chatId)
	);

} catch (\GuzzleHttp\Exception\RequestException $e) {
	
} catch (\GuzzleHttp\Exception\TransferException $e) {
	
} ...
```

**Comment by tje3d** [comment]
Well, i will make proper exception's as soon as i have enough time.

**Comment by marn65** [comment]
you pointed to my problem exactly .
I have some errors in my code,it may be my mistakes,user blocking my bot or even some other sources and APIs I am using have error at the moment.
I want to catch them and avoid telegram to repeat a request again and again.
so with this code
```
try {

	$bot->sendMethod(
		(new \Tje3d\Telegram\Methods\Text())
		    ->text('test')
		    ->chat_id($chatId)
	);

} catch (\GuzzleHttp\Exception\RequestException $e) {
	
} catch (\GuzzleHttp\Exception\TransferException $e) {
	
} ...
```
I will manage any errors come from telegram API, and I must handle my probable errors in my code. am I right?

**Comment by tje3d** [comment]
Yes, but if you want to be quite sure to catch any exception, you have to catch Throwable interface. as any exception extends from `Exception` class and the `Exception` class implements Throwable interface, you will catch any exception and then you can send a response 200.

So the code should be like this:

```
try {

	$bot->sendMethod(
		(new \Tje3d\Telegram\Methods\Text())
		    ->text('test')
		    ->chat_id($chatId)
	);

} catch (Throwable $e) {
	
}
```

**Comment by marn65** [comment]
yeah. very very usefull.
so I can rid of any errors with this last try catch.
very nice :1st_place_medal:

**Comment by mrmrn** [comment]
@tje3d
Dear moen, what do you mean from 

> and then you can send a response 200

```
try {

	$bot->sendMethod(
		(new \Tje3d\Telegram\Methods\Text())
		    ->text('test')
		    ->chat_id($chatId)
	);

} catch (Throwable $e) {
	return 200;
}
```
am I right?
or I must using guzzle or curl to post in telegram server?
and I think it does not work for any kind of problems occure such as `Uncaught ErrorException: Undefined offset: 1 in...`, does it?

**Comment by tje3d** [comment]
@mrmrn i mean a response with http header code 200 ( Standard response for successful HTTP requests ).

```
try {

    $bot->sendMethod(
        (new \Tje3d\Telegram\Methods\Text())
            ->text('test')
            ->chat_id($chatId)
    );

} catch (Throwable $e) {
    return response('Everything was fine', 200);
}

```
